index/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("all/", views.all, name="all"),
    path("about/", views.about, name="about")
    # path("about/#moderation/", views.moderation, name="moderation")
]

petition/urls.py
from django.urls import path
from . import views

app_name='petition'
urlpatterns = [    
    path('', views.index, name='index'),
    path('petitions/<int:petition_id>', views.view_petition, name='view_petition'),
    path('about', views.about, name='about'),
    path('petitions/create', views.create_petition, name='create_petition'),
    path('login', views.login, name='login'),
    path('tags/<slug:tag_label>', views.view_tag, name='view_tag'),
]

# Use static() to add url mapping to serve static files during development (only)
# from django.conf import settings
# from django.conf.urls.static import static


# urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

petitions/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("", include("index.urls")), path("admin/", admin.site.urls)]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

petition/models.py
from django.db import models
from django.utils import timezone

# Creates a tag, there can be at most three in a single petition
class Tag(models.Model):
    label = models.CharField(max_length=15, primary_key=True)	

    # Returns label when asked for the tag 
    def __unicode__(self):
        return self.label	

# Creates a user based on their name, RCS ID and admin status
class User(models.Model):
    rcs_id = models.CharField(max_length=10, primary_key = True)	# RCS ID	
    name = models.CharField(max_length=50)	# The author name
    admin = models.BooleanField(default=False)	# Is admin?
    banned = models.BooleanField(default=False)	# Is the person banned?-- not very likely
    initials = models.CharField(max_length=2)		# Their initials
    union_member = models.BooleanField(default=False)	# Is member of the union?
    
    # Returns their name
    def __unicode__(self):
        return self.rcs_id 	
    
    # Returns the initials of the User using the RCS ID, first strips
    # it of the digits at the end and then 
    def set_initials(self):
        full_name = self.rcs_id
        name_modified = ''.join([i for i in full_name if not i.isdigit()])
        self.initials = name_modified[-1] + name_modified[0]
     
    # Changes the bool value that dictates whether or not a character
    # is a admin
    def set_admin(self,bool_val):
        self.admin = bool_val

# Logs a signature, there can be many in a single petition
class Signature(models.Model):
    signer = models.ForeignKey(User, on_delete=models.CASCADE)	# The person trying to sign the petition
    signed_date = models.DateTimeField(default=timezone.now)	# When they signed 

    # Returns the signer when asked for the initials
    def __unicode__(self):
        return self.signer

# Creates a response based on whether the senate is investigating the topic of the Petition
class Response(models.Model):
    senator_investigation = models.BooleanField(default=False)
    committee_formed = models.BooleanField(default=False)
    vote_resolution = models.BooleanField(default=False)
    vote_referendum = models.BooleanField(default=False)
    refer_to_other = models.BooleanField(default=False)
    
    investigation_info = models.CharField(max_length=1000)
    committee_info = models.CharField(max_length=1000)
    resolution_info = models.CharField(max_length=1000)
    referendum_info = models.CharField(max_length=1000)
    refer_other_info = models.CharField(max_length=1000)

    # If there is a senate investigation in place, set 
    # senator_investigation to true, false otherwise
    def set_senate(self,bool_val):
        self.senator_investigation = bool_val
        
    # If there was a committee creates, set 
    # committee_formed to true, false otherwise
    def set_committee (self,bool_val):
        self.committee_formed = bool_val

    # If there was a resolution voted on, set 
    # vote_resolution to true, false otherwise
    def set_resolution (self,bool_val):
        self.vote_resolution = bool_val

    # If there was a referendum voted on, set 
    # vote_referendum to true, false otherwise
    def set_referendum (self,bool_val):
        self.vote_referendum = bool_val

    # If some other action was taken/ referred to another group,
    # set refer_to_other to true, false otherwise
    def set_other (self,bool_val):
        self.refer_to_other = bool_val

    # Add information for the senate investigation
    def add_info_senate(self,info):
        self.investigation_info = info
        return self.investigation_info
    # Add information on the committee assigned to help
    def add_info_committee (self,info):
        self.committee_info = info
        return self.committee_info
    # Add information on the resolution that was voted on
    def add_info_resolution (self,info):
        self.resolution_info = info
        return self.resolution_info
    # Add information on the referendum that wsa voted on
    def add_info_referendum (self,info):
        self.referendum_info = info
        return self.referendum_info
    # Add information on the other group that the issue was
    # referred to
    def add_info_other (self, info):
        self.refer_other_info = info
        return self.refer_other_info

class Petition(models.Model):
    title = models.CharField(max_length=200)	# Title of petition
    description = models.CharField(max_length=4000)	# The paragraph description
    archived = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
                
    created_date = models.DateTimeField(db_index=True, default=timezone.now)	# Files the date created
    expected_sig = models.IntegerField()		# The expected signature to move to the next step

    author = models.ForeignKey(User, on_delete=models.CASCADE)	# The author of the petition
    tags = models.ManyToManyField(Tag)	# The tags, probably a max of 3
    signatures = models.ManyToManyField(Signature)	# The signature

    senate_response = models.ForeignKey(Response, on_delete=models.CASCADE)		# If the senate has responded , their answer

    # Returns title when asked for the item
    def __unicode__(self):
        return self.title		
  
       # Sets the hidden variable as true if we don't want it to
       # Be displayed in the main site
    def set_hidden(self, bool_val):
        self.hidden = bool_val

    # If the petition isn't active, we can set the archived variable as true
    def set_archived(self, bool_val):
        self.archived = bool_val

    # Adds a description to the basic petitions model, with a max length
    # of 4000 words
    def add_description(self, descript):
        self.description = descript
        return True
    # Returns true if we have enough signatures on the petition
    def check_enough_sigs(self):
        if self.signatures.all().count() >= self.expected_sig:
            return True
        return False
    # Makes sure the we have less than three tags in the model
    def check_tags(self):
        if self.tags.all().count() > 3:
            return False
        return True

    # Add tag to a petition, there can be at most three in a single petition
    #def add_tag (self):

petition/views.py
from django.shortcuts import render, get_object_or_404
from .models import Petition

def index(request):
    return render(request, 'index.html', {'petitions': Petition.objects.all()})

def view_petition(request, petition_id):
    return render(request, 'view-petition.html', {'petition': get_object_or_404(Petition, pk=petition_id)})

def about(request):
    return render(request, 'about.html')

def create_petition(request):
    return render(request, 'create-petition.html')

def login(request):
    return render(request, 'login.html')

def view_tag(request, tag_label):
    return render(request, 'view-tag.html')

petition/templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>About</h1>
<p>TODO</p>
{% endblock %}

petition/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">        
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> 
        {% load static %}
        <link rel="shortcut icon" href="{%  static 'petition/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'petition/style.css' %}">
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light">
          <div class="container">
              <img class="petitions-logo" src="{% static 'petition/petitions.png' %}">
              <a class="navbar-brand mr-auto pontiac" href="{% url 'petition:index' %}">RPI Petitions</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'petition:index' %}">View All</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'petition:create_petition' %}">Create</a>
                  </li>
                </ul>
                <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'petition:about' %}">About</a>
                  </li>
                  <li class="nav-item">
                      <a class="btn btn-secondary" href="{% url 'petition:login' %}">Login</a>
                  </li>
                </ul>
              </div>
          </div>
        </nav>

        <div class="main">
            {% block content %}{% endblock %}
        </div>

        <footer class="footer">
            <div class="container">
                <span class="text-muted">
                    <p>This is an <a href="https://github.com/wtg">open source</a> project made and maintained by the Web Technologies Group of the Rensselaer Union Student Senate</p></span>
                <a href="https://webtech.union.rpi.edu/">
                    <img class="wtg-logo" src="{% static 'petition/wtg.svg' %}">
                </a>
            </div>
        </footer>
    
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>    
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

petition/templates/create-petition.html
{% extends "base.html" %}
{% block content %}
<h1>Create petition</h1>
<p>TODO</p>
{% endblock %}

petition/templates/index.html
{% extends "base.html" %}
{% block title %}RPI Petitions{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="caption">
        <h1 class="pontiac">Student Senate Petitions</h1>
        <h4>Create and sign petitions.</h4>
        <h4>Make your voice heard by the RPI Student Senate and the campus community.</h4>
    </div>    
</div>

<div class="container">
    <div class="header"><h4>Recent Petitions</h4></div>    
    <div class="grid">    
        {% for petition in petitions %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'petition:view_petition' petition.id %}">{{ petition.title }}</a></h5>
                    <h6 class="card-subtitle mb-2">{{ petition.signatures.all.count }} signatures</h6>
                    {% for tag in petition.tags.all %}
                        <a href="{% url 'petition:view_tag' tag.label %}" class="link">{{ tag.label }}</a><br>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

 <!-- Add view all petitions button -->
 <!-- <div class="container">
    <a class="btn btn-outline-danger" id="view-all" href="./view_all.html">View All Petitions</a>
 </div> -->

{% endblock %}

petition/templates/login.html
{% extends "base.html" %}
{% block content %}
<h1>Login</h1>
<p>TODO</p>
{% endblock %}

petition/templates/view-petition.html
{% extends "base.html" %}
{% block content %}
<h1>{{ petition.title }}</h1>
<p>Description: {{ petition.description }}</p>

{% endblock %}

petition/templates/view-tag.html
{% extends "base.html" %}
{% block content %}
<h1>View petitions by tag</h1>
<p>TODO</p>
{% endblock %}